{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lanshifu.plugin",
    "module": "privacy_method",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "privacy_method-1.0.0-beta01.jar",
          "url": "privacy_method-1.0.0-beta01.jar",
          "size": 68918,
          "sha512": "aff8e625b609c590c35cc1ddc2999c85e74e0715bee612358e39c569e3b30069dea728fb0ec71678323679bd098fd245abc0914eef4e66de126c52811d6e1e6e",
          "sha256": "82ff3f4684b56681a52ead0977a1f325a7eaab4ad84bf27a87146b288608f67b",
          "sha1": "8d68a220a8b6b9d5d4f3de464001c572045ddbbc",
          "md5": "0603bea05bb07b833cfacb837cfc9779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "privacy_method-1.0.0-beta01.jar",
          "url": "privacy_method-1.0.0-beta01.jar",
          "size": 68918,
          "sha512": "aff8e625b609c590c35cc1ddc2999c85e74e0715bee612358e39c569e3b30069dea728fb0ec71678323679bd098fd245abc0914eef4e66de126c52811d6e1e6e",
          "sha256": "82ff3f4684b56681a52ead0977a1f325a7eaab4ad84bf27a87146b288608f67b",
          "sha1": "8d68a220a8b6b9d5d4f3de464001c572045ddbbc",
          "md5": "0603bea05bb07b833cfacb837cfc9779"
        }
      ]
    }
  ]
}
